// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

class RenderRequest {
  RenderRequest({
    required this.sourcePath,
    required this.startMillis,
    required this.endMillis,
    required this.resolution,
    required this.frameRate,
    required this.codec,
    required this.targetWidth,
    required this.targetHeight,
    required this.cropToPortrait,
    required this.requiresReencode,
    this.captionSegments,
    this.watermark,
  });

  String sourcePath;

  int startMillis;

  int endMillis;

  String resolution;

  String frameRate;

  String codec;

  int targetWidth;

  int targetHeight;

  bool cropToPortrait;

  bool requiresReencode;

  List<RenderCaptionSegment?>? captionSegments;

  RenderWatermarkConfig? watermark;

  Object encode() {
    return <Object?>[
      sourcePath,
      startMillis,
      endMillis,
      resolution,
      frameRate,
      codec,
      targetWidth,
      targetHeight,
      cropToPortrait,
      requiresReencode,
      captionSegments,
      watermark,
    ];
  }

  static RenderRequest decode(Object result) {
    result as List<Object?>;
    return RenderRequest(
      sourcePath: result[0]! as String,
      startMillis: result[1]! as int,
      endMillis: result[2]! as int,
      resolution: result[3]! as String,
      frameRate: result[4]! as String,
      codec: result[5]! as String,
      targetWidth: result[6]! as int,
      targetHeight: result[7]! as int,
      cropToPortrait: result[8]! as bool,
      requiresReencode: result[9]! as bool,
      captionSegments: (result[10] as List<Object?>?)
          ?.cast<RenderCaptionSegment?>(),
      watermark: result[11] as RenderWatermarkConfig?,
    );
  }
}

class RenderWatermarkConfig {
  RenderWatermarkConfig({
    this.text,
    this.imagePath,
    required this.anchor,
    this.customX,
    this.customY,
    required this.opacity,
    required this.scale,
  });

  String? text;

  String? imagePath;

  String anchor;

  double? customX;

  double? customY;

  double opacity;

  double scale;

  Object encode() {
    return <Object?>[text, imagePath, anchor, customX, customY, opacity, scale];
  }

  static RenderWatermarkConfig decode(Object result) {
    result as List<Object?>;
    return RenderWatermarkConfig(
      text: result[0] as String?,
      imagePath: result[1] as String?,
      anchor: result[2]! as String,
      customX: result[3] as double?,
      customY: result[4] as double?,
      opacity: result[5]! as double,
      scale: result[6]! as double,
    );
  }
}

class RenderCaptionSegment {
  RenderCaptionSegment({
    required this.text,
    required this.startMillis,
    required this.endMillis,
  });

  String text;

  int startMillis;

  int endMillis;

  Object encode() {
    return <Object?>[text, startMillis, endMillis];
  }

  static RenderCaptionSegment decode(Object result) {
    result as List<Object?>;
    return RenderCaptionSegment(
      text: result[0]! as String,
      startMillis: result[1]! as int,
      endMillis: result[2]! as int,
    );
  }
}

class RenderResult {
  RenderResult({
    required this.cachePath,
    this.galleryUri,
    this.resolution,
    this.frameRate,
    this.codec,
    this.targetWidth,
    this.targetHeight,
    this.cropToPortrait,
    this.requiresReencode,
  });

  String cachePath;

  String? galleryUri;

  String? resolution;

  String? frameRate;

  String? codec;

  int? targetWidth;

  int? targetHeight;

  bool? cropToPortrait;

  bool? requiresReencode;

  Object encode() {
    return <Object?>[
      cachePath,
      galleryUri,
      resolution,
      frameRate,
      codec,
      targetWidth,
      targetHeight,
      cropToPortrait,
      requiresReencode,
    ];
  }

  static RenderResult decode(Object result) {
    result as List<Object?>;
    return RenderResult(
      cachePath: result[0]! as String,
      galleryUri: result[1] as String?,
      resolution: result[2] as String?,
      frameRate: result[3] as String?,
      codec: result[4] as String?,
      targetWidth: result[5] as int?,
      targetHeight: result[6] as int?,
      cropToPortrait: result[7] as bool?,
      requiresReencode: result[8] as bool?,
    );
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is RenderRequest) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is RenderWatermarkConfig) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is RenderCaptionSegment) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is RenderResult) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return RenderRequest.decode(readValue(buffer)!);
      case 130:
        return RenderWatermarkConfig.decode(readValue(buffer)!);
      case 131:
        return RenderCaptionSegment.decode(readValue(buffer)!);
      case 132:
        return RenderResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class NativeRenderApi {
  /// Constructor for [NativeRenderApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NativeRenderApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<RenderResult> exportTrim(RenderRequest request) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.langgeng_clip.NativeRenderApi.exportTrim$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[request]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as RenderResult?)!;
    }
  }

  Future<void> cancelExport() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.langgeng_clip.NativeRenderApi.cancelExport$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}
