// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.langgeng.langgeng_clip.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class RenderRequest (
  val sourcePath: String,
  val startMillis: Long,
  val endMillis: Long,
  val resolution: String,
  val frameRate: String,
  val codec: String,
  val targetWidth: Long,
  val targetHeight: Long,
  val cropToPortrait: Boolean,
  val requiresReencode: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RenderRequest {
      val sourcePath = pigeonVar_list[0] as String
      val startMillis = pigeonVar_list[1] as Long
      val endMillis = pigeonVar_list[2] as Long
      val resolution = pigeonVar_list[3] as String
      val frameRate = pigeonVar_list[4] as String
      val codec = pigeonVar_list[5] as String
      val targetWidth = pigeonVar_list[6] as Long
      val targetHeight = pigeonVar_list[7] as Long
      val cropToPortrait = pigeonVar_list[8] as Boolean
      val requiresReencode = pigeonVar_list[9] as Boolean
      return RenderRequest(sourcePath, startMillis, endMillis, resolution, frameRate, codec, targetWidth, targetHeight, cropToPortrait, requiresReencode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sourcePath,
      startMillis,
      endMillis,
      resolution,
      frameRate,
      codec,
      targetWidth,
      targetHeight,
      cropToPortrait,
      requiresReencode,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RenderResult (
  val cachePath: String,
  val galleryUri: String? = null,
  val resolution: String? = null,
  val frameRate: String? = null,
  val codec: String? = null,
  val targetWidth: Long? = null,
  val targetHeight: Long? = null,
  val cropToPortrait: Boolean? = null,
  val requiresReencode: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RenderResult {
      val cachePath = pigeonVar_list[0] as String
      val galleryUri = pigeonVar_list[1] as String?
      val resolution = pigeonVar_list[2] as String?
      val frameRate = pigeonVar_list[3] as String?
      val codec = pigeonVar_list[4] as String?
      val targetWidth = pigeonVar_list[5] as Long?
      val targetHeight = pigeonVar_list[6] as Long?
      val cropToPortrait = pigeonVar_list[7] as Boolean?
      val requiresReencode = pigeonVar_list[8] as Boolean?
      return RenderResult(cachePath, galleryUri, resolution, frameRate, codec, targetWidth, targetHeight, cropToPortrait, requiresReencode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      cachePath,
      galleryUri,
      resolution,
      frameRate,
      codec,
      targetWidth,
      targetHeight,
      cropToPortrait,
      requiresReencode,
    )
  }
}
private open class RenderApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RenderRequest.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RenderResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is RenderRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is RenderResult -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NativeRenderApi {
  fun exportTrim(request: RenderRequest, callback: (Result<RenderResult>) -> Unit)
  fun cancelExport(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by NativeRenderApi. */
    val codec: MessageCodec<Any?> by lazy {
      RenderApiPigeonCodec()
    }
    /** Sets up an instance of `NativeRenderApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeRenderApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.langgeng_clip.NativeRenderApi.exportTrim$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as RenderRequest
            api.exportTrim(requestArg) { result: Result<RenderResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.langgeng_clip.NativeRenderApi.cancelExport$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.cancelExport{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
